# Generated by Django 5.1.7 on 2025-03-16 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_sold',
            new_name='is_on_sale',
        ),
    ]
